### ISSUE TITLE
Scheduling a pod that requests a specific type of GPU

### ISSUE THREAD

**Issue by naved001** [OCP-on-NERC/apps#336]
I know we have node feature discovery that automatically labels nodes and I guess one could request a specific type of GPU by using those labels. I have some questions about this:

1. Do we prevent non GPU pods from running on GPU pods? [This document ](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#example-use-cases)describes a possible solution.

2. How do we enforce quota for specific GPU types? This [document talks](https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-for-extended-resources) about setting quota on a gpu but I don't know it can enforce the type of GPU and not just the count.

I am asking these question in the context of billing, mainly to determine the type of GPU a pod is consuming. If it's going to be part of the pod definition somewhere and the pod is scheduled to run then that might be the best way of saying what GPU a pod is using.

**Comment by joachimweyl** [comment]
@jtriley where do we currently stand with managing different types of GPUs in Openshift?

**Comment by joachimweyl** [comment]
Are we able to test this with the single A100 and the few V100s we have in OpenShift Prod?

**Comment by larsks** [comment]
@joachimweyl  I would like to relocate this issue to https://github.com/nerc-project/operations/, but since I am not an owner of the target organization I can't move it. We could just close it here and re-create it there.

**Comment by joachimweyl** [comment]
moved to https://github.com/nerc-project/operations/issues/447
