### ISSUE TITLE
Vault's pod disruption budget is keeping the cluster from upgrading

### ISSUE THREAD

**Issue by naved001** [OCP-on-NERC/apps#59]
@chrisstafford mentioned this on slack and I figured we should have this here so we can resolve this before the next upgrade.

**Comment by joachimweyl** [comment]
@chrisstafford can you provide more detail on this issue?

**Comment by joachimweyl** [comment]
Worth noting that Vault was sealed due to this issue.

**Comment by larsks** [comment]
@naved001 should we move this to [operations](https://github.com/OCP-on-NERC/operations/) or close it?

**Comment by naved001** [comment]
let's just close this.
